### ISSUE TITLE
Error in postman export 

### ISSUE THREAD

**Issue by danielerizzoarchivi** [fsoft72/restest#3]
When I launch the restest command with the --postman parameter (e.g. **restest <actionsX.json> --postman <actionX_postman.json>** ) I get the "AttributeError" error on line 41 of ./lib/postman_exp.py ( _parse_body). The function expects a dictionary but returns a string

**Comment by danielerizzoarchivi** [comment]
this workaround ( https://github.com/fsoft72/restest/pull/2  ) solves the problem

**Comment by fsoft72** [comment]
Thanks, I merged it into main branch.
You are the first contributor :smile: 
Welcome
